import { useState } from "react";

interface HoldingRisk { security_id: string; quantity: number; market_value: string | number; unrealized_return?: string | number | null; risk_status: string; stop_breached: boolean; reasons: string[] }
interface HoldingResult { portfolio_id: string; equity: string | number; exposure_ratio: string | number; portfolio_drawdown: string | number; warnings: string[]; risks: HoldingRisk[] }
export function HoldingsPage(): JSX.Element {
  const [portfolioId, setPortfolioId] = useState("default"); const [asOfTime, setAsOfTime] = useState(() => new Date().toISOString().slice(0, 16)); const [prices, setPrices] = useState("{}"); const [result, setResult] = useState<HoldingResult | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const submit = async (): Promise<void> => { setLoading(true); setError(null); try { const parsed: unknown = JSON.parse(prices || "{}"); const response = await fetch("/api/v1/holdings/analysis", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ portfolio_id: portfolioId, as_of_time: new Date(asOfTime).toISOString(), prices: parsed }) }); if (!response.ok) throw new Error(`持仓分析请求失败（${response.status}）`); setResult(await response.json() as HoldingResult); } catch (err) { setError(err instanceof SyntaxError ? "价格必须是合法 JSON" : err instanceof Error ? err.message : "请求失败"); } finally { setLoading(false); } };
  return <section><h2>持仓分析</h2><p>查看持仓敞口、回撤与止损状态。</p><label>组合 ID <input value={portfolioId} onChange={(e) => setPortfolioId(e.target.value)} /></label><label>分析时点 <input type="datetime-local" value={asOfTime} onChange={(e) => setAsOfTime(e.target.value)} /></label><label>最新价格 JSON <input value={prices} onChange={(e) => setPrices(e.target.value)} /></label><button onClick={() => void submit()} disabled={loading || !portfolioId}>{loading ? "分析中…" : "分析持仓"}</button>{error && <p role="alert">{error}</p>}{result && <div><p>权益：{result.equity}　敞口：{result.exposure_ratio}　组合回撤：{result.portfolio_drawdown}</p>{result.warnings.map((warning) => <p key={warning} role="status">⚠ {warning}</p>)}<table><thead><tr><th>代码</th><th>数量</th><th>市值</th><th>收益率</th><th>风险</th></tr></thead><tbody>{result.risks.map((risk) => <tr key={risk.security_id}><td>{risk.security_id}</td><td>{risk.quantity}</td><td>{risk.market_value}</td><td>{risk.unrealized_return ?? "—"}</td><td>{risk.stop_breached ? "止损触发" : risk.risk_status}</td></tr>)}</tbody></table></div>}</section>;
}

export const holdingsFeature = {
  id: "holdings", path: "/holdings", label: "持仓分析", element: <HoldingsPage />,
} as const;
